title: "Speech Accessibility Project Challenge 2"
description: "Welcome to the Speech Accessibility Project Challenge 2. This challenge seeks to rapidly advance the state of the art in dysarthric speech recognition."
theme: jekyll-theme-primer

url: "https://xiuwenz2.github.io"
baseurl: "/SAPC2-website"

markdown: kramdown
permalink: pretty
future: true

header_pages:
  - timeline.md
  - leaderboard.md
  - track1.md
  - track2.md
  - faqs.md
