title: "Speech Accessibility Project Challenge 2"
description: "Welcome to the Speech Accessibility Project Challenge 2. This challenge seeks to rapidly advance the state of the art in dysarthric speech recognition."
theme: jekyll-theme-minimal

url: "https://xiuwenz2.github.io"
baseurl: "/SAPC2-website"

markdown: kramdown
permalink: pretty

# Optional: show future-dated posts/pages if you add them later
future: true
